// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["jquery", "underscore", "backbone"], function($, _, Backbone) {
    'use strict';
    var BlessingModel, _ref;

    return BlessingModel = (function(_super) {
      __extends(BlessingModel, _super);

      function BlessingModel() {
        _ref = BlessingModel.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      return BlessingModel;

    })(Backbone.Model);
  });

}).call(this);
